// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHnqh4_qq_xKsxN8fHCOswSkrITu4wW8',
    appId: '1:410405925296:web:e65cb9d98ac75d3bbc2675',
    messagingSenderId: '410405925296',
    projectId: 'golf-live-scoring-559c4',
    authDomain: 'golf-live-scoring-559c4.firebaseapp.com',
    storageBucket: 'golf-live-scoring-559c4.firebasestorage.app',
    measurementId: 'G-ZX040S2NW9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GsAZqCmYO6kN7RMhYF10iRQC2FRXnUs',
    appId: '1:410405925296:android:bf1d14ff19461805bc2675',
    messagingSenderId: '410405925296',
    projectId: 'golf-live-scoring-559c4',
    storageBucket: 'golf-live-scoring-559c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6lNVZrwNShNLI1iJNO9ZFwU6t46mD5fc',
    appId: '1:410405925296:ios:a60cfc1be19bef6bbc2675',
    messagingSenderId: '410405925296',
    projectId: 'golf-live-scoring-559c4',
    storageBucket: 'golf-live-scoring-559c4.firebasestorage.app',
    androidClientId: '410405925296-jll2evalflpmcuaer8l6pt81q1qev52k.apps.googleusercontent.com',
    iosClientId: '410405925296-t4ks55okvqaut257qp38jep0e8ea86gc.apps.googleusercontent.com',
    iosBundleId: 'net.alexplay.golflivescoring.golfLiveScoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6lNVZrwNShNLI1iJNO9ZFwU6t46mD5fc',
    appId: '1:410405925296:ios:a60cfc1be19bef6bbc2675',
    messagingSenderId: '410405925296',
    projectId: 'golf-live-scoring-559c4',
    storageBucket: 'golf-live-scoring-559c4.firebasestorage.app',
    androidClientId: '410405925296-jll2evalflpmcuaer8l6pt81q1qev52k.apps.googleusercontent.com',
    iosClientId: '410405925296-t4ks55okvqaut257qp38jep0e8ea86gc.apps.googleusercontent.com',
    iosBundleId: 'net.alexplay.golflivescoring.golfLiveScoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgHnqh4_qq_xKsxN8fHCOswSkrITu4wW8',
    appId: '1:410405925296:web:0068038f35c055d8bc2675',
    messagingSenderId: '410405925296',
    projectId: 'golf-live-scoring-559c4',
    authDomain: 'golf-live-scoring-559c4.firebaseapp.com',
    storageBucket: 'golf-live-scoring-559c4.firebasestorage.app',
    measurementId: 'G-FNNXFF0P4W',
  );

}